name: Dependabot Jira

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.txt'
      - '*.MD'
      - '*.md'
      - 'LICENSE'
      - 'docs/**'

env:
  JIRA_BASE_URL: 'https://githubtraining.atlassian.net'
  JIRA_USER_EMAIL: 'rohitnb@github.com'
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  JIRA_PROJECT: 'RNB'
  JIRA_ISSUE_TYPE: 'Task'

jobs:
  create_jira:
    name: Dependabot Jira
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' #id dependabot user
    steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ env.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ env.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ env.JIRA_API_TOKEN }}

    - name: Create Jira Issue
      id: create
      uses: atlassian/gajira-create@v2.0.1
      with:
        project: ${{ env.JIRA_PROJECT }}
        issuetype: ${{ env.JIRA_ISSUE_TYPE }}
        summary: |
          [${{github.event.repository.name }}] ${{github.event.pull_request.title }}
        description: |
          ${{github.event.pull_request.html_url }}